### ISSUE TITLE
Add plant pathology and weed science as accepted categories

### ISSUE THREAD

**Issue by adamhsparks** [jpiaskowski/ctv-agriculture#1]
First, this is a great initiative! Thank you for starting this, I’m excited to see it.

I see entomology listed, I’d like to see plant pathology and weed science included as well or maybe just a broader “crop protection” category with some of these as possible examples?

**Comment by adamhsparks** [comment]
Also, how can I help?

**Comment by jpiaskowski** [comment]
Hello! Thank you and welcome! 

Yes, I think the categories listed are up for discussion and revision. For example, the package "drc" most certainly belongs in a weed science category. In many cases, it will make sense to send people to other CRAN task views (e.g. "TimeSeries" for ag economics, "Spatial" for soils). 

You're more than welcome to contribute. I've volunteered to handle the agronomic and genetics section (it currently says "plant genetics" but I think it should encompass plant and animal genetics and breeding). Another person is working on the "soil science" category (this category is broad and may be broken into smaller sub-categories). Once those sections are up, feedback is welcome. 

Is there any area you would like to contribute to? 

Each section will contain a brief synopsis of major packages to address the topic. Not every single package needs to be mentioned. This is intended to be a curated guide, not an unabridged dictionary of every last package relevant to agricultural research. 

For now, please put your additions into this file [task_view_ideas.md](https://github.com/jpiaskowski/ctv-agriculture/blob/main/task_view_ideas.md). I recommend you write up your section(s), but refrain from editing other sections at this time (just to make merging easier for me). 

And please add your name to the authors list if you contribute.

**Comment by adamhsparks** [comment]
Specifically, I'd be happy to contribute to plant pathology, but I'm happy to help wherever I can and it's welcome.

**Comment by jpiaskowski** [comment]
Perfect, I look forward to your contribution.
