### ISSUE TITLE
Course materials suggestion for “Links”

### ISSUE THREAD

**Issue by adamhsparks** [jpiaskowski/ctv-agriculture#40]
Some years ago I was involved in writing a set of course materials for self-instruction or classroom that demonstrate epidemiological concepts in R for plant pathologists.

This would be a nice addition to the “Links”, I think.

https://www.apsnet.org/edcenter/disimpactmngmnt/topc/EcologyAndEpidemiologyInR/Pages/default.aspx

**Comment by jpiaskowski** [comment]
Sounds good to me. I'm about to push a change (just chasing down issues), but after that, it's all yours.

**Comment by jpiaskowski** [comment]
all done!

**Comment by adamhsparks** [comment]
Closed with https://github.com/cran-task-views/Agriculture/commit/ba53d06b1ce5273a4b03ebd7038455838da5e03c
